rabbitmq:
  queue:
    name: "hello-cv2"

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

    servlet:
      multipart:
        max-file-size: 128KB
        max-request-size: 128KB

logging:
  level:
    org: INFO
